# Generated by Django 5.2.4 on 2025-08-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, help_text='Message or preferred name for appointment', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or specific concerns', null=True),
        ),
    ]
