# Generated by Django 5.2.4 on 2025-09-07 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether reminder email has been sent'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['reminder_sent', 'date', 'time'], name='backend_app_reminde_583b12_idx'),
        ),
    ]
