# Generated by Django 5.2.4 on 2025-08-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_appointment_message_appointment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
    ]
